### ISSUE TITLE
Mod no longer loads/mod cannot be removed

### ISSUE THREAD

**Issue by FrankTheReal** [qstar-inc/cities2-SimpleModChecker#1]
Hello, I have a very serious problem with the mod. 

Since I installed the mod, no other mod from my list loads. In addition, I can no longer uninstall the mod. When I delete it via the Paradox Mod Manager, it still seems to be active because I see "Mods loading" in the notifications. Even a complete reinstallation didn't help

**Comment by qstar-inc** [comment]
From version 1.1.2f1, the base game itself now has a mod-checking notification. It is not from Simple Mod Checker. If mods aren't loading, you might try using Skyve and/or create a new playset. Either way, contact with the people of Discord servers if you want more help as this is out of the scope of this mod.
